package io.euhedral_execution.training.packaging;

public enum ArtifactSemanticType {
    PACKAGE_README,
    MERGE_DATASET,
    VECTOR_ONLY_DATASET,
    VECTOR_WITH_MEASUREMENTS_DATASET,
    HUMAN_READABLE_REPORT,
    MODEL_METADATA,
    MODEL_EVALUATION_DATASET,
    MODEL_MEMBER_PARAMETERS,
    SCHEDULE_DATASET,
    COMPLETION_MARKER,
    CHECKPOINT_STATE,
    CHECKPOINT_SIDECAR,
    PACKAGE_REPRODUCTION_INPUT,
    RAW_DATA_INDEX,
    RAW_RUN_METADATA,
    RAW_POLICY_CATALOG,
    RAW_OBSERVATIONS
}
