[tools]
apple-codesign = "latest"
java = "corretto-25.0.2.10.1"
maven = "latest"
rust = "latest"
zig = "0.16.0"

[tool_alias]
apple-codesign = "cargo:apple-codesign"

[env]
SDKROOT   = "{{env.HOME}}/.local/share/mise/installs/macos-sdk"
