/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":euhedral-core"))
    api(project(":euhedral-data-structures"))
    api(project(":euhedral-hardware-utils"))
    api(project(":euhedral-hashing"))
    api(libs.org.apache.commons.commons.math4.legacy)
    api(libs.org.jspecify.jspecify)
    api(libs.ai.djl.api)
    api(libs.ai.djl.pytorch.pytorch.engine)
    api(libs.org.slf4j.slf4j.api)
    runtimeOnly(libs.ai.djl.pytorch.pytorch.jni)
    runtimeOnly(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.assertj.assertj.core)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

description = "Euhedral Training"
