"""Pareto Weight Calibration Package.

Ingestion, validation, and calibration dataset pipeline for Euhedral Execution.
"""

from pareto_weight_calibration.audit import (
    build_dataset,
    compute_bounded_family_influence,
    get_physical_family_id,
    perform_identifiability_audit,
)
from pareto_weight_calibration.constraints import (
    MODEL_STRUCTURES,
    build_physical_corner_matrix,
    build_projected_scaled_constraint_matrix,
    check_corner_constraints,
    get_domain_corners,
    load_domain_config,
    save_domain_config,
    verify_fixed_state_prefix_monotonicity,
)
from pareto_weight_calibration.cv import (
    FoldResult,
    LOFOGridResult,
    LOFOResult,
    compute_fold_influence_weights,
    execute_lofo_grid_search,
    run_single_lofo_candidate,
)
from pareto_weight_calibration.device import (
    DTYPE,
    is_cuda,
    is_cuda_available,
    resolve_device,
    to_numpy,
    to_tensor,
)
from pareto_weight_calibration.diagnostics import (
    AdjacentLambdaSensitivityResult,
    CommonReferenceRepresentation,
    FixedStatePrefixDiagnosticResult,
    LowConfidenceAblationResult,
    StabilityComparison,
    build_common_reference_scales,
    compare_common_reference_stability,
    compute_common_reference_representation,
    diagnose_fixed_state_prefix,
    evaluate_direct_physical_marginal,
    run_adjacent_lambda_sensitivity,
    run_low_confidence_ablation,
    verify_evaluator_parity,
    verify_evaluator_parity_grid,
)
from pareto_weight_calibration.eligibility import (
    EligibilityAuditor,
    EligibilityError,
)
from pareto_weight_calibration.evaluate import (
    EvaluationMetrics,
    ObservationLoss,
    compute_fixed_cutoff_logits,
    compute_observation_loss,
    evaluate_always_cache,
    evaluate_always_participate,
    evaluate_fixed_cutoff,
    evaluate_predictions,
    extract_record_evidence_basis,
    select_best_fixed_cutoff_on_train,
)
from pareto_weight_calibration.export import export_pairs_tsv
from pareto_weight_calibration.loader import DataLoader
from pareto_weight_calibration.loss import (
    compute_probabilities,
    loss_gradient,
    loss_hessian,
    unclipped_binary_cross_entropy,
    weighted_regularized_loss,
)
from pareto_weight_calibration.model import (
    JavaParetoWeights,
    LogicalWeights,
    MarginalModel,
)
from pareto_weight_calibration.nested import (
    STANDARD_LAMBDA_GRID,
    STRUCTURE_SIZES,
    STRUCTURE_SPECIFICATIONS,
    ModelStructure,
    ParsimonyComparison,
    ParsimonySelectionResult,
    compare_candidate_metrics,
    embed_active_weights,
    evaluate_parsimony_conditions,
    execute_procedural_parsimony,
    extract_active_weights,
    select_best_lambda_for_structure,
)
from pareto_weight_calibration.optimizer import (
    OptimizationResult,
    compute_kkt_stationarity_residual,
    fit_constrained_model,
)
from pareto_weight_calibration.scaling import (
    back_transform_weights,
    compute_training_scales,
    scale_features,
    transform_weights_to_scaled,
    verify_scale_invariance,
)
from pareto_weight_calibration.types import (
    ActiveStateFeatures,
    ArmPerformance,
    ArtifactEligibility,
    Dataset,
    DomainConfig,
    ForkThroughput,
    IdentifiabilityAuditResult,
    LabelEvidenceBasis,
    Manifest,
    ManifestPair,
    Outcome,
    PairRecord,
    TrajectoryStatus,
    TrialConfig,
    WithdrawnDiagnosticState,
)

__version__ = "0.1.0"
__all__ = [
    "ActiveStateFeatures",
    "AdjacentLambdaSensitivityResult",
    "ArmPerformance",
    "ArtifactEligibility",
    "CommonReferenceRepresentation",
    "DTYPE",
    "DataLoader",
    "Dataset",
    "DomainConfig",
    "EligibilityAuditor",
    "EligibilityError",
    "EvaluationMetrics",
    "FixedStatePrefixDiagnosticResult",
    "FoldResult",
    "ForkThroughput",
    "IdentifiabilityAuditResult",
    "JavaParetoWeights",
    "LOFOGridResult",
    "LOFOResult",
    "LabelEvidenceBasis",
    "LogicalWeights",
    "LowConfidenceAblationResult",
    "Manifest",
    "ManifestPair",
    "MarginalModel",
    "ModelStructure",
    "ObservationLoss",
    "OptimizationResult",
    "Outcome",
    "PairRecord",
    "ParsimonyComparison",
    "ParsimonySelectionResult",
    "STANDARD_LAMBDA_GRID",
    "STRUCTURE_SIZES",
    "STRUCTURE_SPECIFICATIONS",
    "StabilityComparison",
    "back_transform_weights",
    "build_common_reference_scales",
    "build_dataset",
    "build_physical_corner_matrix",
    "build_projected_scaled_constraint_matrix",
    "check_corner_constraints",
    "compare_candidate_metrics",
    "compare_common_reference_stability",
    "compute_bounded_family_influence",
    "compute_common_reference_representation",
    "compute_fixed_cutoff_logits",
    "compute_fold_influence_weights",
    "compute_kkt_stationarity_residual",
    "compute_observation_loss",
    "compute_probabilities",
    "compute_training_scales",
    "diagnose_fixed_state_prefix",
    "embed_active_weights",
    "evaluate_always_cache",
    "evaluate_always_participate",
    "evaluate_direct_physical_marginal",
    "evaluate_fixed_cutoff",
    "evaluate_parsimony_conditions",
    "evaluate_predictions",
    "execute_lofo_grid_search",
    "execute_procedural_parsimony",
    "export_pairs_tsv",
    "extract_active_weights",
    "extract_record_evidence_basis",
    "fit_constrained_model",
    "get_domain_corners",
    "get_physical_family_id",
    "is_cuda",
    "is_cuda_available",
    "load_domain_config",
    "loss_gradient",
    "loss_hessian",
    "perform_identifiability_audit",
    "resolve_device",
    "run_adjacent_lambda_sensitivity",
    "run_low_confidence_ablation",
    "run_single_lofo_candidate",
    "save_domain_config",
    "scale_features",
    "select_best_fixed_cutoff_on_train",
    "select_best_lambda_for_structure",
    "to_numpy",
    "to_tensor",
    "transform_weights_to_scaled",
    "unclipped_binary_cross_entropy",
    "verify_evaluator_parity",
    "verify_evaluator_parity_grid",
    "verify_fixed_state_prefix_monotonicity",
    "verify_scale_invariance",
    "weighted_regularized_loss",
]
