/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

// Note: Repositories are configured centrally in settings.gradle.kts
// and project-level repository declarations are forbidden

group = "io.euhedral-execution"
version = "0.0.7-SNAPSHOT"

// Default Java version - can be overridden in individual modules
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

dependencies {
    // Add JUnit Platform Launcher for test execution
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.5")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-parameters")
}

// Add lombok annotation processing configuration
configurations {
    compileOnly {
        extendsFrom(configurations.annotationProcessor.get())
    }
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.withType<Test>() {
    useJUnitPlatform()
}
