package io.euhedral_execution.core.control_plane;

/// Generated by pareto_weight_calibration.logistic_runtime; do not edit.
/// Candidate: logistic-05-sqrt
/// Training artifact SHA-256: f382e9d306d0a0cbb70213383459d002ef856e6f3902c7b7537291f6916c15dc
/// Dataset SHA-256: bee6cdcb324fb1c2c68788bf6cbb2783723fde617521dc09621af7ea9447e4a3
/// Exporter version: logistic-java-exporter-v1
final class ParticipationLogisticModel {
    static final String CANDIDATE_ID = "logistic-05-sqrt";
    static final String TRAINING_ARTIFACT_SHA256 = "f382e9d306d0a0cbb70213383459d002ef856e6f3902c7b7537291f6916c15dc";
    static final String DATASET_SHA256 = "bee6cdcb324fb1c2c68788bf6cbb2783723fde617521dc09621af7ea9447e4a3";
    static final String EXPORTER_VERSION = "logistic-java-exporter-v1";
    static final double PROBABILITY_THRESHOLD = 0.45;
    static final double LOGIT_THRESHOLD = -0.20067069546215124;
    static final double INTERCEPT = -2.643817471080609;

    private ParticipationLogisticModel() {}

    static boolean shouldCache(
            int k, long productiveHandles, int registeredWorkers, double bodyCostNs, double contention) {
        return score(k, productiveHandles, registeredWorkers, bodyCostNs, contention) >= LOGIT_THRESHOLD;
    }

    static double score(int k, long productiveHandles, int registeredWorkers, double bodyCostNs, double contention) {
        double pRatio = (double) productiveHandles / registeredWorkers;
        double logR = Math.log(registeredWorkers);
        double body = Math.log1p(bodyCostNs);
        double zK = (k - 4.319044216248458) / 4.1181433661913065;
        double zPRatio = (pRatio - 0.4622763757547462) / 0.33724380301220946;
        double zLogR = (logR - 2.667804090854188) / 0.4901351282564824;
        double zBody = (body - 4.65009657333485) / 0.9912481295736798;
        double zContention = (contention - 0.4474590877565059) / 0.38529526416306775;

        double result = INTERCEPT;
        result += 0.4241650904189753 * zK;
        result += -0.2031033180323249 * zPRatio;
        result += 0.0 * zLogR;
        result += -0.6314678834474282 * zBody;
        result += 0.7694883160744411 * zContention;
        result += 0.0 * zK * zPRatio;
        result += -0.03395423986927718 * zK * zBody;
        result += 0.44259833262386755 * zK * zContention;
        result += 0.08703074460828884 * zBody * zPRatio;
        result += -0.1853465591892819 * zContention * zPRatio;
        result += -1.581531213003884 * zBody * zContention;
        return result;
    }
}
