/*
 * This file was generated by the Gradle 'init' task.
 */

import java.nio.file.Files

plugins {
    id("buildlogic.java-conventions")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

val nativeGeneratedResources = layout.buildDirectory.dir("generated-resources/native")
val generatedJniDir = layout.buildDirectory.dir("generated-jni")

// Generate JNI headers during compilation and set module version
tasks.named<JavaCompile>("compileJava") {
    options.compilerArgs.addAll(
        listOf(
            "-h", generatedJniDir.get().file("declarations").asFile.absolutePath,
            "--module-version", version.toString()
        )
    )
    // Suppress platform version in module-info to match Maven behavior
    options.compilerArgs.add("--release")
    options.compilerArgs.add("17")
}

// Task to clean native resources before build
val cleanNativeResources by tasks.registering {
    doLast {
        fun deleteWithoutFollowingSymlinks(path: File) {
            if (!path.exists()) return
            if (path.isDirectory && !Files.isSymbolicLink(path.toPath())) {
                path.listFiles()?.forEach { deleteWithoutFollowingSymlinks(it) }
                path.delete()
            } else {
                path.delete()
            }
        }
        
        val nativeDir = nativeGeneratedResources.get().asFile
        deleteWithoutFollowingSymlinks(nativeDir)
        
        val binDir = file("${layout.buildDirectory.get()}/classes/java/main/bin")
        deleteWithoutFollowingSymlinks(binDir)
        
        val manifestFile =
            file("${layout.buildDirectory.get()}/classes/java/main/META-INF/euhedral/native-products.tsv")
        if (manifestFile.exists()) {
            manifestFile.delete()
        }
    }
}

val zigBuild by tasks.registering(Exec::class) {
    dependsOn(tasks.named("compileJava"))
    dependsOn(cleanNativeResources)

    val zigExec = System.getenv("ZIG") ?: "zig"
    val javaHome = System.getProperty("java.home")
    val sdkRoot = System.getenv("SDKROOT") ?: ""
    val rcodeSign = System.getenv("RCODESIGN") ?: ""

    workingDir = file("src/main/native")
    commandLine = listOf(
        zigExec,
        "build",
        "-Djava-home=$javaHome",
        "-Dgenerated-jni=${generatedJniDir.get().asFile.absolutePath}",
        "-Doutput-root=${nativeGeneratedResources.get().asFile.absolutePath}",
        "-Dmacos-sdk=$sdkRoot",
        "-Drcodesign=$rcodeSign",
        "--cache-dir", "${layout.projectDirectory}/zig-cache",
        "--global-cache-dir", "${layout.projectDirectory}/zig-global-cache"
    )

    inputs.dir("src/main/native")
    inputs.dir(generatedJniDir)
    outputs.dir(nativeGeneratedResources)
}

// Task to copy native resources to output
val copyNativeResources by tasks.registering(Copy::class) {
    dependsOn(zigBuild)

    from(nativeGeneratedResources) {
        include("bin/**")
        include("META-INF/euhedral/native-products.tsv")
    }
    // Copy to classes directory to match Maven behavior (Gradle separates classes and resources)
    into(sourceSets.main.get().output.classesDirs.singleFile)
}

// Make classes task depend on native build
tasks.named("classes") {
    dependsOn(copyNativeResources)
}

// Configure JAR to include Maven metadata
tasks.named<Jar>("jar") {
    // Add Maven metadata to match Maven-built JARs
    into("META-INF/maven/${project.group}/${project.name}") {
        // Copy the module's pom.xml
        from("${project.projectDir}/pom.xml")
        // Generate pom.properties
        val pomProperties = """
            #Generated by Gradle
            version=${project.version}
            groupId=${project.group}
            artifactId=${project.name}
        """.trimIndent()
        from(provider {
            val propsFile = File(temporaryDir, "pom.properties")
            propsFile.writeText(pomProperties)
            files(propsFile)
        })
    }
}

// Task to prepare native smoke test bundle
tasks.register<Copy>("prepareNativeSmokeBundle") {
    dependsOn(tasks.named("jar"))
    dependsOn(tasks.named("testClasses"))

    val smokeDir = file("${layout.buildDirectory.get()}/native-smoke")

    // Copy the JAR
    from(tasks.jar.get().archiveFile) {
        into(".")
    }

    // Copy test class
    from("${layout.buildDirectory.get()}/classes/java/test/io/euhedral_execution/hardware_utils/internal/NativeLoadSmokeMain.class") {
        into("io/euhedral_execution/hardware_utils/internal")
    }

    // Copy runtime dependencies
    from(configurations.runtimeClasspath) {
        into("lib")
    }

    into(smokeDir)
}

// Make test depend on smoke bundle preparation
tasks.named("test") {
    dependsOn("prepareNativeSmokeBundle")
}

// Configure test system properties
tasks.named<Test>("test") {
    systemProperty("p0.project.basedir", project.projectDir.absolutePath)
    systemProperty("p0.classes.directory", sourceSets.main.get().output.classesDirs.asPath)
    systemProperty("p0.build.directory", layout.buildDirectory.get().asFile.absolutePath)
    systemProperty("p1.rcodesign", System.getenv("RCODESIGN") ?: "")
    systemProperty("p1.llvm.readobj", System.getenv("LLVM_READOBJ") ?: "/usr/bin/llvm-readobj")
    systemProperty("p1.llvm.objdump", System.getenv("LLVM_OBJDUMP") ?: "/usr/bin/llvm-objdump")
    systemProperty("p1.jar", tasks.jar.get().archiveFile.get().asFile.absolutePath)
    systemProperty("p1.smoke.directory", "${layout.buildDirectory.get()}/native-smoke")
    systemProperty("p1.test.classes", sourceSets.test.get().output.classesDirs.asPath)
}

dependencies {
    api(libs.it.unimi.dsi.fastutil)
    api(libs.org.slf4j.slf4j.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.ow2.asm.asm)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
    compileOnly(libs.org.jspecify.jspecify)
}

description = "Euhedral Hardware Utils"
